"""
db_store.py
-----------
Drop-in replacement for csv_store.py.

Behaviour:
  - Reads and writes local CSV files exactly as CSVStore did (CSVs remain the
    session-level cache and source of truth for Python scripts).
  - ALSO appends every write operation to data/pending_writes.jsonl so that
    Claude can flush those writes to Databricks after each pipeline phase using
    the db_sync.py helpers and the execute_sql() MCP tool.

Usage (unchanged from csv_store.py):
    from db_store import DBStore as CSVStore
    store = DBStore(data_dir="/path/to/data")
    store.upsert_lead(fields)
    store.log_activity(gwc_id, activity_type, detail)

Databricks tables (claude_prototyping.marketing):
    leads_maturity       ← upsert_lead / update_lead_field
    lead_activity_log    ← log_activity
    country_rep_mapping  ← read-only via lookup_reps (never written here)
"""

import csv
import io as _io
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Optional


# ── Column definitions (must match CSV headers exactly) ───────────────────────

LEADS_COLUMNS = [
    "id", "gwc_id", "email_message_id", "contact_name", "company_name",
    "phone", "whatsapp", "from_country", "to_country", "origin_country_alt",
    "destination_country_alt", "mode_of_freight", "container_mode",
    "container_type", "product", "perishable", "temperature_details",
    "stackable", "dg_class", "msds", "incoterms", "weight_kg", "volume_m3",
    "packages", "chargeable_weight", "dimension_lwh", "shipping_requirements",
    "notes", "classification", "missing_fields", "current_status",
    "status_history", "assigned_rep_email", "assigned_rep_name",
    "assigned_country", "hubspot_create_date", "email_received_at",
    "first_response_at", "quote_sent_at", "follow_up_started_at",
    "deal_confirmed_at", "deal_outcome", "lead_age_days", "reminder_history",
    "created_at", "updated_at", "last_email_scan_at",
    "notes_quality_score", "extensia_feedback",
    "in_quip_sheet", "quip_country", "quip_updates_raw", "quip_updates_summary",
    "bd_poc_name", "bd_poc_email",
    "detected_working_rep_email", "detected_working_rep_name",
    "routed_at",
]

ACTIVITY_COLUMNS = [
    "id", "gwc_id", "activity_type", "activity_detail",
    "email_message_id", "performed_by", "created_at",
]

# Databricks target (for reference; SQL is generated by db_sync.py)
DB_CATALOG  = "claude_prototyping"
DB_SCHEMA   = "marketing"
DB_LEADS    = f"{DB_CATALOG}.{DB_SCHEMA}.leads_maturity"
DB_ACTIVITY = f"{DB_CATALOG}.{DB_SCHEMA}.lead_activity_log"
DB_MAPPING  = f"{DB_CATALOG}.{DB_SCHEMA}.country_rep_mapping"


class DBStore:
    """
    CSVStore-compatible store that also queues writes for Databricks sync.

    Public interface is identical to CSVStore. Drop-in safe.
    """

    def __init__(self, data_dir: str):
        self.data_dir     = Path(data_dir)
        self.leads_path   = self.data_dir / "leads_maturity.csv"
        self.activity_path = self.data_dir / "lead_activity_log.csv"
        # Use v2 file (with new reps added 2026-04-23) when available
        _mapping_v2 = self.data_dir / "country_rep_mapping_v2.csv"
        self.mapping_path = _mapping_v2 if _mapping_v2.exists() else self.data_dir / "country_rep_mapping.csv"
        self.queue_path   = self.data_dir / "pending_writes.jsonl"

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _read_csv(self, path: Path) -> list[dict]:
        if not path.exists():
            return []
        with open(path, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            return list(reader)

    def _write_csv(self, path: Path, rows: list[dict], columns: list[str]):
        buf = _io.StringIO()
        writer = csv.DictWriter(buf, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
        content = buf.getvalue().encode("utf-8")
        if path.exists():
            fd = os.open(str(path), os.O_WRONLY | os.O_TRUNC)
            try:
                os.write(fd, content)
            finally:
                os.close(fd)
        else:
            with open(path, "wb") as f:
                f.write(content)

    def _next_id(self, rows: list[dict]) -> int:
        if not rows:
            return 1
        try:
            return max(int(r.get("id", 0) or 0) for r in rows) + 1
        except (ValueError, TypeError):
            return len(rows) + 1

    def _now(self) -> str:
        return datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    def _enqueue(self, op: str, **payload):
        """Append a write operation to pending_writes.jsonl."""
        entry = {"op": op, "ts": self._now(), **payload}
        with open(self.queue_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    # ── Leads ─────────────────────────────────────────────────────────────────

    def get_all_gwc_ids(self) -> set:
        rows = self._read_csv(self.leads_path)
        return {r["gwc_id"] for r in rows if r.get("gwc_id")}

    def get_lead(self, gwc_id: str) -> Optional[dict]:
        rows = self._read_csv(self.leads_path)
        for r in rows:
            if r.get("gwc_id") == gwc_id:
                return r
        return None

    def upsert_lead(self, fields: dict) -> dict:
        """
        Insert or update a lead row (matched by gwc_id).
        Writes to CSV and queues a Databricks MERGE operation.
        """
        rows = self._read_csv(self.leads_path)
        now  = self._now()

        existing_idx = None
        for i, r in enumerate(rows):
            if r.get("gwc_id") == fields.get("gwc_id"):
                existing_idx = i
                break

        if existing_idx is not None:
            row = rows[existing_idx]
            for col in LEADS_COLUMNS:
                if col in ("id", "created_at"):
                    continue
                if fields.get(col) not in (None, ""):
                    row[col] = fields[col]
            row["updated_at"] = now
            rows[existing_idx] = row
        else:
            row = {col: fields.get(col, "") for col in LEADS_COLUMNS}
            row["id"] = self._next_id(rows)
            if not row.get("created_at"):
                row["created_at"] = now
            row["updated_at"] = now
            rows.append(row)

        self._write_csv(self.leads_path, rows, LEADS_COLUMNS)

        # Queue for Databricks (full row MERGE)
        self._enqueue("upsert_lead", gwc_id=row["gwc_id"], data=dict(row))
        return row

    def update_lead_field(self, gwc_id: str, updates: dict) -> bool:
        """
        Update specific fields on an existing lead.
        Writes to CSV and queues a Databricks UPDATE operation.
        """
        rows = self._read_csv(self.leads_path)
        now  = self._now()
        found = False
        for r in rows:
            if r.get("gwc_id") == gwc_id:
                r.update(updates)
                r["updated_at"] = now
                found = True
                break

        if found:
            self._write_csv(self.leads_path, rows, LEADS_COLUMNS)
            # Queue for Databricks (partial UPDATE)
            self._enqueue("update_lead", gwc_id=gwc_id,
                          data={**updates, "updated_at": now})
        return found

    # ── Activity log ──────────────────────────────────────────────────────────

    def log_activity(
        self,
        gwc_id: str,
        activity_type: str,
        detail: dict,
        email_message_id: str = "",
        performed_by: str = "SYSTEM",
    ) -> dict:
        """
        Append an entry to lead_activity_log.csv.
        Also queues a Databricks INSERT operation.
        """
        rows = self._read_csv(self.activity_path)
        row = {
            "id":              self._next_id(rows),
            "gwc_id":          gwc_id,
            "activity_type":   activity_type,
            "activity_detail": json.dumps(detail),
            "email_message_id": email_message_id,
            "performed_by":    performed_by,
            "created_at":      self._now(),
        }
        rows.append(row)
        self._write_csv(self.activity_path, rows, ACTIVITY_COLUMNS)

        # Queue for Databricks (INSERT)
        self._enqueue("insert_activity", data=dict(row))
        return row

    # ── Country → rep mapping (read-only) ────────────────────────────────────

    def lookup_reps(self, country_name: str, primary_only: bool = False) -> list[dict]:
        """
        Look up sales reps for a destination country.
        Read-only — never written here; managed in Databricks directly.
        """
        rows = self._read_csv(self.mapping_path)
        country_lower = (country_name or "").lower().strip()

        aliases = {
            "saudi arabia":           "ksa",
            "ksa":                    "ksa",
            "kingdom of saudi arabia":"ksa",
            "bahrain":                "ba",
            "united arab emirates":   "uae",
            "u.a.e":                  "uae",
            "uae":                    "uae",
            "qatar":                  "qatar",
            "oman":                   "oman",
        }
        normalised = aliases.get(country_lower, country_lower)

        matched = []
        for r in rows:
            if r.get("active", "").upper() != "TRUE":
                continue
            row_country  = (r.get("country_name") or "").lower()
            row_aliases  = aliases.get(row_country, row_country)
            if (normalised in row_country
                    or row_country in normalised
                    or normalised == row_aliases):
                if primary_only and r.get("is_primary", "").upper() != "TRUE":
                    continue
                matched.append(r)

        return matched

    # ── Queue inspection helpers (called by Claude, not pipeline scripts) ─────

    def queue_size(self) -> int:
        """Return number of pending write operations in the queue."""
        if not self.queue_path.exists():
            return 0
        with open(self.queue_path, encoding="utf-8") as f:
            return sum(1 for line in f if line.strip())

    def clear_queue(self):
        """Empty the queue after a successful Databricks flush."""
        self.queue_path.write_text("", encoding="utf-8")


# ── Backward-compat alias ─────────────────────────────────────────────────────
CSVStore = DBStore
